# Generated by Django 3.0.4 on 2020-03-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='btype',
            new_name='type',
        ),
    ]
